# Generated by Django 2.2.1 on 2019-05-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=130, null=True)),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('weight', models.IntegerField(default=0, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.CenterModel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('is_dilivered', models.BooleanField(default=False)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LoadModel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='LoadDistanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CenterModel')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LoadModel')),
            ],
        ),
        migrations.CreateModel(
            name='CenterDistanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('center_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='main.CenterModel')),
                ('center_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='main.CenterModel')),
            ],
        ),
    ]
