# Generated by Django 2.2.1 on 2019-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190518_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
